### ISSUE TITLE
Enable VPN on source NAT IP for network

### ISSUE THREAD

**Issue by gurubert** [xanzy/terraform-provider-cloudstack#53]
Hi,

### Terraform Version
Terraform v0.11.11
+ provider.cloudstack v0.2

A cloudstack network offering can enable an L2TP IPsec VPN on its source NAT IP.

It would be nice if this could be configured via terraform.

**Comment by gurubert** [comment]
Hi @svanharmelen ,

I found these API calls:
https://cloudstack.apache.org/api/apidocs-4.9/apis/createRemoteAccessVpn.html
https://cloudstack.apache.org/api/apidocs-4.9/apis/addVpnUser.html

The ```publicipid``` should be the ID of the automatically configured source NAT IP of an isolated network or maybe could be any IP that has been configured.
The ```presharedkey``` and the ```publicip``` are the imporant information bits after the VPN has been configured.

**Comment by svanharmelen** [comment]
Ah, check... Adding support for this would require creating new resources, but I'm currently not working with CloudStack anymore. So I'm mostly maintaining and improving the resources that currently exist (in my own time) as I don't have time to work on new resources in my current job.

But If someone in the community wants to add this, I'm of course open to PRs 😉

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-terraform-provider
