### ISSUE TITLE
Add new resource: Project

### ISSUE THREAD

**Issue by 3guboff** [xanzy/terraform-provider-cloudstack#62]
Hi,

Would be really good, if someone can add resource - Project  (cloudstack_project) for better experience in using CS provider. It's important resource because almost always new environment in CS starting from this step.

Thank you for reviewing this issue.

**Comment by svanharmelen** [comment]
Hi @3guboff! Adding support for this would require creating a new resource, but I'm currently not working with CloudStack anymore. So I'm mostly maintaining and improving the resources that already exist (in my own time) as I don't have time to work on new resources in my current job.

But If someone in the community wants to add this, I'm of course open to PRs 😉

**Comment by 3guboff** [comment]
Ok @svanharmelen, I'm started development new resource - **project** and it's almost done.

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-terraform-provider
