### ISSUE TITLE
Fix documentation for cloudstack_loadbalancer_rule

### ISSUE THREAD

**Issue by mmaldonado-wtsh** [xanzy/terraform-provider-cloudstack#66]
Hi,

Changing member_ids does not force a new resource to be created, despite what the documentation mentions.

Regards,

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-terraform-provider
