### ISSUE TITLE
Cannot pass data to custom service-offering

### ISSUE THREAD

**Issue by ckayhuo** [xanzy/terraform-provider-cloudstack#73]
Hi all,
Terraform Cloudstack Provider is unable to pass arguments for custom compute offering on CloudStack. To use a custom compute offering it has to provide the following three arguments but in the CS provider there is no way we can pass them to the server.

details[0].cpuNumber: 2
details[0].cpuSpeed: 2000
details[0].memory: 2000

### Terraform Version
Terraform v0.12.18

### Affected Resource(s)
- opc_instance

### Expected Behavior
Able to pass arguments to a custom service offering to deploy a VM on CloudStack

### Actual Behavior
Error: Error creating the new instance test-tf: CloudStack API error 431 (CSExceptionErrorCode: 4350): Need to specify custom parameter values cpu, cpu speed and memory when using custom offering

### Steps to Reproduce
1. create a "cloudstack_instance" resource, and set service_offering = ID of the custom service offering
2. terraform apply

### References
https://github.com/atsaki/terraform-provider-cloudstack/issues/1

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-terraform-provider
