### ISSUE TITLE
cloudstack_port_forward does not work

### ISSUE THREAD

**Issue by gurubert** [xanzy/terraform-provider-cloudstack#74]
Hi,

### Terraform Version
Terraform v0.12.24
+ provider.cloudstack v0.3.0

### Affected Resource(s)
- cloudstack_port_forward

### Panic Output
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.trainer.cloudstack_port_forward.client01-ssh will be created
  + resource "cloudstack_port_forward" "client01-ssh" {
      + id            = (known after apply)
      + ip_address_id = "794aca7d-032c-4dbc-8706-a01c5ba5810c"
      + managed       = false

      + forward {
          + private_port       = 22
          + protocol           = "tcp"
          + public_port        = 2222
          + uuid               = (known after apply)
          + virtual_machine_id = "bb06fbb6-c657-455a-8892-5fb2d6a35eac"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.trainer.cloudstack_port_forward.client01-ssh: Creating...
module.trainer.cloudstack_port_forward.client01-ssh: Still creating... [10s elapsed]

Error: Provider produced inconsistent result after apply

When applying changes to module.trainer.cloudstack_port_forward.client01-ssh,
provider "registry.terraform.io/-/cloudstack" produced an unexpected new value
for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior
The port forwarding has been created without an error in terraform's execution.

### Actual Behavior
The port forwarding has been created, but terraform throws an error.

**Comment by gurubert** [comment]
The resource `cloudstack_firewall` has the same issue.

**Comment by svanharmelen** [comment]
Does this happen with older versions of TF as well? Say the latest 0.11.x and/or an early 0.12.x?

And which version of CloudStack are you using?

**Comment by gurubert** [comment]
We are running CloudStack 4.11

Terraform 0.12.1 has the same issue. I am not able to test with Terraform 0.11, as the configuration has already been migrated.

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-terraform-provider
