### ISSUE TITLE
Add cloudstack_network datasource

### ISSUE THREAD

**Issue by apevrier** [xanzy/terraform-provider-cloudstack#75]
Hello,

In order to support deployment strategies where networks are managed independently from instances, having a network datasource would be quite useful.

This enhancement would use a syntax similar to the currently existing cloudstack_template datasource :
```hcl
data "cloudstack_network" "my_network" {
  filter {
    name = "name"
    value = "private_network"
  }

  filter {
    name = "cidr"
    value = "10.0.0.0/24"
  }
}
```

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-terraform-provider
