### ISSUE TITLE
Terraform doesn't work with ASC 4.15

### ISSUE THREAD

**Issue by Lucasgranet** [xanzy/terraform-provider-cloudstack#79]
Hi there,

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/terraform-providers/cloudstack v0.3.0

### Affected Resource(s)
At least:
- cloudstack_security_group
- cloudstack_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "cloudstack" {
  api_url    = var.cloudstack_api_url
  api_key    = var.cloudstack_api_key
  secret_key = var.cloudstack_secret_key
}

resource "cloudstack_security_group" "default" {
  name        = "allow_web"
  description = "Allow access to HTTP and HTTPS"
}


resource "cloudstack_security_group_rule" "web" {

  security_group_id = cloudstack_security_group.default.id

  rule {
    cidr_list = ["0.0.0.0/0"]
    protocol  = "tcp"
    ports     = ["80", "443"]
  }

}


resource "cloudstack_instance" "web" {
  name             = "server-1"
  service_offering = "004c5ceb-6f48-4cbf-bd9a-435921a0d539"
  network_id       = "c32328f6-956d-4b2c-80eb-3b56876e06e3"
  template         = "Ubuntu 18.04"
  zone             = "25856f21-9121-4401-9f80-fb1ad35a06d:"
  expunge          = "true"
}


#This resource is made to allow Terraform to output the list of Hosts into the Ansible's inventory file
resource "null_resource" "provisioning"{
    provisioner "local-exec" {
      command = "rm -f provisioning/inventory/hosts && mkdir -p provisioning/inventory/ && /usr/bin/echo -e '[web]\n${cloudstack_instance.web.ip_address}' > provisioning/inventory/hosts"
    }
}

```

### Debug Output
https://gist.github.com/Lucasgranet/3cfc4eca06ecb5d7b83f89c7b410b1a2

### Panic Output
N/A

### Expected Behavior
Should create defined ressources.

### Actual Behavior
Crash and provide following error :
```
cloudstack_security_group.default: Creating...
cloudstack_instance.web: Creating...

Error: Error creating security group allow_web: invalid character '<' looking for beginning of value

  on web.tf line 7, in resource "cloudstack_security_group" "default":
   7: resource "cloudstack_security_group" "default" {



Error: Error retrieving ID of zone 25856f21-9121-4401-9f80-fb1ad35a06d:: invalid character '<' looking for beginning of value

  on web.tf line 26, in resource "cloudstack_instance" "web":
  26: resource "cloudstack_instance" "web" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
No

### References
No

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-terraform-provider
